name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24.x']

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: go mod tidy
        run: go mod tidy
      - name: Run fmt
        run: |
          if [ "$(go fmt ./... | wc -l)" -gt 0 ]; then
              exit 1
          fi
      - name: Run Tests
        run: go test -v ./...
      - name: Must be A+
        run: |
          cd ..
          git clone https://github.com/gojp/goreportcard.git
          cd goreportcard
          make install
          go install ./cmd/goreportcard-cli
          cd ../ionq-go
          goreportcard-cli
          if [ "$(goreportcard-cli -j | jq '.GradeFromPercentage')" != "A+" ]; then
            exit 1
          fi

      
